jobs:
  build:
    annotations:
        screwdriver.cd/disk: HIGH
        screwdriver.cd/ram: HIGH
        screwdriver.cd/buildPeriodically: H * * * *
    secrets:
        - BINTRAY_USER
        - BINTRAY_API_KEY
        # Remove SCM_* secrets once project is public
        - SCM_USERNAME
        - SCM_ACCESS_TOKEN
    environment:
      VERSION: $SD_EVENT_ID
    image: maven:3.6.3-jdk-8-openj9
    requires: [~pr, ~commit]
    steps:
      - test_and_publish: |
          if [ ! -z $SD_PULL_REQUEST ]; then
            echo Skipping publish in PR build
            mvn clean test
          else
             mvn versions:set -DnewVersion=1.5.${VERSION} -DprocessAllModules=true
             mvn -B clean deploy --settings ./settings.xml
          fi
